### ISSUE TITLE
Unable to install this package

### ISSUE THREAD

**Issue by SSMK-wq** [djdeepak72/ziln_cltv#1]
Hi, I tried following your instruction and install the package based on your readme file but it threw the below error.

Is there anyway that you can help resolve this error please?

I wrote the below line
`
pip install https://github.com/djdeepak72/ziln-cltv.git`

below error

![image](https://user-images.githubusercontent.com/30723825/199932481-63ad24f3-09ab-4994-9df9-377736564fc3.png)

**Comment by ghost** [comment]
Apologies. I've updated the readme file: 
Use this command: 
pip install git+https://github.com/djdeepak72/ziln_cltv.git
